export type MenuCategory =
  | "همه"
  | "صبحانه"
  | "سالاد و سوپ"
  | "پاستا"
  | "باگت"
  | "دسر"
  | "ماكتيل"
  | "نوشیدنی بر پایه اسپرسو"
  | "قهوه هاى دمى"
  | "فراپه"
  | "شیک و اسموتی"
  | "ماچا"
  | "نوشیدنی گازدار"
  | "نوشیدنی های گرم"
  | "دمنوش ها"
  | "آیسد تی"
  | "افزودنی ها";

export type ProductVariant = {
  id: string;
  nameFa: string;
  nameEn: string;
  price: number;
};

export type MenuItem = {
  id: string;
  slug: string;
  nameFa: string;
  nameEn: string;
  description: string | null;
  price: number;
  category: Exclude<MenuCategory, "همه">;
  image: string;
  tag: string | null;
  time: string;
  ingredients: string[];
  note: string | null;

  variants?: ProductVariant[];
  selectedVariant?: ProductVariant;
};

export const categories: MenuCategory[] = [
  "همه",
  "صبحانه",
  "سالاد و سوپ",
  "پاستا",
  "باگت",
  "دسر",
  "ماكتيل",
  "نوشیدنی بر پایه اسپرسو",
  "قهوه هاى دمى",
  "فراپه",
  "شیک و اسموتی",
  "ماچا",
  "نوشیدنی گازدار",
  "نوشیدنی های گرم",
  "دمنوش ها",
  "آیسد تی",
  "افزودنی ها",
];

export const menuItems: MenuItem[] = [
  {
    slug: "fry-up",
    nameFa: "فرای آپ",
    nameEn: "Fry Up",
    description:
      "سوسیس انجوی دست ساز، دو عدد نیمرو، بیکن فیله گوشت، قارچ گریل، گوجه چری، نان تست خمیر ترش، لوبیا",
    price: 698000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202511041000515041821.jpeg",
    tag: "پیشنهاد ویژه",
    ingredients: [
      "سوسیس انجوی دست ساز",
      "دو عدد نیمرو",
      "بیکن فیله گوشت",
      "قارچ گریل",
      "گوجه چری",
      "نان تست خمیر ترش",
      "لوبیا",
    ],
    note: null,
    id: "01",
    time: "20 دقیقه",
  },
  {
    slug: "oliva-omelette",
    nameFa: "املت اولیوا",
    nameEn: "Oliva Omelette",
    description:
      "تخم مرغ، زیتون اسلایس شده، سس پومودورو، رب انار، گردو، گوجه خشک مزه دارشده",
    price: 439000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240241420546189.jpg",
    tag: null,
    ingredients: [
      "تخم مرغ",
      "زیتون اسلایس شده",
      "سس پومودورو",
      "رب انار",
      "گردو",
      "گوجه خشک مزه دارشده",
    ],
    note: null,
    id: "02",
    time: "20 دقیقه",
  },
  {
    slug: "charmont-omelette",
    nameFa: "املت شارمونت",
    nameEn: "Charmont Omelette",
    description:
      "تخم مرغ، سس پومودورو، ریحان ایتالیایی، پنیر تازه، گوجه خشک مزه دارشده",
    price: 419000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240242213989055.jpg",
    tag: null,
    ingredients: [
      "تخم مرغ",
      "سس پومودورو",
      "ریحان ایتالیایی",
      "پنیر تازه",
      "گوجه خشک مزه دارشده",
    ],
    note: null,
    id: "03",
    time: "20 دقیقه",
  },
  {
    slug: "bacon-toast",
    nameFa: "تست بیکن",
    nameEn: "Bacon Toast",
    description:
      "نان تست بر پایه خمیر ترش، پنیر لبنه، بیکن فیله گوشت، تخم مرغ اسکرامبل، کاهو فرانسوی، گوجه خشک، زیتون، سس مایوچیز دست ساز، به همراه سالاد با سس انار عسل",
    price: 579000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240242423366838.jpg",
    tag: null,
    ingredients: [
      "نان تست بر پایه خمیر ترش",
      "پنیر لبنه",
      "بیکن فیله گوشت",
      "تخم مرغ اسکرامبل",
      "کاهو فرانسوی",
      "گوجه خشک",
      "زیتون",
      "سس مایوچیز دست ساز",
      "به همراه سالاد با سس انار عسل",
    ],
    note: null,
    id: "04",
    time: "20 دقیقه",
  },
  {
    slug: "enjoy-toast",
    nameFa: "تست اینجوی",
    nameEn: "Enjoy Toast",
    description:
      "نان تست بر پایه خمیر ترش، سوسیس دست ساز انجوی، پنیر لبنه، تخم مرغ نیمرو، گوجه خشک، کاهو فرانسوی، زیتون، دیپ دودی، به همراه سالاد با سس انار عسل",
    price: 589000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240243145558676.jpg",
    tag: null,
    ingredients: [
      "نان تست بر پایه خمیر ترش",
      "سوسیس دست ساز انجوی",
      "پنیر لبنه",
      "تخم مرغ نیمرو",
      "گوجه خشک",
      "کاهو فرانسوی",
      "زیتون",
      "دیپ دودی",
      "به همراه سالاد با سس انار عسل",
    ],
    note: null,
    id: "05",
    time: "20 دقیقه",
  },
  {
    slug: "stocky-toast",
    nameFa: "تست استیک",
    nameEn: "Stocky Toast",
    description:
      "نان تست بر پایه خمیر ترش، فیله گوساله مزه‌دار شده، تخم مرغ نیمرو، گوجه خشک مزه دار شده، زیتون، کاهو فرانسوی، سس پینات اسموکی، به همراه سالاد با سس انار عسل",
    price: 789000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240243445875247.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: [
      "نان تست بر پایه خمیر ترش",
      "فیله گوساله مزه‌دار شده",
      "تخم مرغ نیمرو",
      "گوجه خشک مزه دار شده",
      "زیتون",
      "کاهو فرانسوی",
      "سس پینات اسموکی",
      "به همراه سالاد با سس انار عسل",
    ],
    note: null,
    id: "06",
    time: "20 دقیقه",
  },
  {
    slug: "spinach-toast",
    nameFa: "تست اسفناج",
    nameEn: "Spinach Toast",
    description:
      "نان تست بر پایه خمیر ترش، قارچ کاراملایز، تخم مرغ اسکرامبل، اسفناج، گوجه خشک مزه دار شده، زیتون، کاهو فرانسوی، به همراه سالاد با سس انار عسل",
    price: 569000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240244071972031.jpg",
    tag: null,
    ingredients: [
      "نان تست بر پایه خمیر ترش",
      "قارچ کاراملایز",
      "تخم مرغ اسکرامبل",
      "اسفناج",
      "گوجه خشک مزه دار شده",
      "زیتون",
      "کاهو فرانسوی",
      "به همراه سالاد با سس انار عسل",
    ],
    note: null,
    id: "07",
    time: "20 دقیقه",
  },
  {
    slug: "peanutbutter-toast",
    nameFa: "تست کره بادام زمینی",
    nameEn: "PeanutButter Toast",
    description:
      "نان تست بر پایه خمیر ترش، کره بادام زمینی کرانچی، موز، عسل، خامه حجیم شده، به همراه میوه‌های فصل",
    price: 398000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240247011683218.jpg",
    tag: null,
    ingredients: [
      "نان تست بر پایه خمیر ترش",
      "کره بادام زمینی کرانچی",
      "موز",
      "عسل",
      "خامه حجیم شده",
      "به همراه میوه‌های فصل",
    ],
    note: null,
    id: "08",
    time: "20 دقیقه",
  },
  {
    slug: "french-toast",
    nameFa: "فرنچ تست",
    nameEn: "French Toast",
    description:
      "دو عدد نان بریوش آغشته به تخم مرغ و شیر و کمی دارچین، تست شده در کره و سیروپ افرا به همراه موز و توت فرنگی و بلوبری",
    price: 489000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202606061831344827835.jpeg",
    tag: "پیشنهاد ویژه",
    ingredients: [
      "دو عدد نان بریوش آغشته به تخم مرغ و شیر و کمی دارچین",
      "تست شده در کره و سیروپ افرا به همراه موز و توت فرنگی و بلوبری",
    ],
    note: null,
    id: "09",
    time: "20 دقیقه",
  },
  {
    slug: "orange-cool-up",
    nameFa: "آب پرتقال",
    nameEn: "Orange Cool up",
    description: "آب پرتقال طبیعی",
    price: 270000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202511031815125559011.jpeg",
    tag: null,
    ingredients: ["آب پرتقال طبیعی"],
    note: null,
    id: "10",
    time: "20 دقیقه",
  },
  {
    slug: "red-cool-up",
    nameFa: "آب هندوانه",
    nameEn: "Red Cool up",
    description: "آب هندوانه طبیعی",
    price: 210000,
    category: "صبحانه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505241649517429328.JPG",
    tag: null,
    ingredients: ["آب هندوانه طبیعی"],
    note: null,
    id: "11",
    time: "20 دقیقه",
  },
  {
    slug: "viande-salad",
    nameFa: "سالاد ویانده",
    nameEn: "Viande Salad",
    description:
      "کاهو فرانسوی ، فیله گوساله مزه دار شده، لوبیا ، زیتون ، هویج ژول ، گوجه گیلاسی ، سس خردل دستساز",
    price: 727000,
    category: "سالاد و سوپ",
    image:
      "https://img01.live-app.ir/Files/394/Product/202311121421200756317.jpg",
    tag: null,
    ingredients: [
      "کاهو فرانسوی",
      "فیله گوساله مزه دار شده",
      "لوبیا",
      "زیتون",
      "هویج ژول",
      "گوجه گیلاسی",
      "سس خردل دستساز",
    ],
    note: null,
    id: "12",
    time: "20 دقیقه",
  },
  {
    slug: "shandy-salad",
    nameFa: "سالاد شندی",
    nameEn: "Shandy Salad",
    description:
      "کاهو پیچ، مرغ مزه دار شده، پنیر پارمسان‌،نان کروتان، سس دستساز ریحان ایتالیایی و گردو، زیتون، گوجه چری، کیپرس",
    price: 629000,
    category: "سالاد و سوپ",
    image:
      "https://img01.live-app.ir/Files/394/Product/202510171924487176196.jpg",
    tag: null,
    ingredients: [
      "کاهو پیچ",
      "مرغ مزه دار شده",
      "پنیر پارمسان‌",
      "نان کروتان",
      "سس دستساز ریحان ایتالیایی و گردو",
      "زیتون",
      "گوجه چری",
      "کیپرس",
    ],
    note: null,
    id: "13",
    time: "20 دقیقه",
  },
  {
    slug: "pomodoro-pasta",
    nameFa: "پاستا پومودورو",
    nameEn: "Pomodoro Pasta",
    description:
      "پنه‌ ریگاته، سس پومودورو برپایه گوجه رست شده، ریحان ایتالیایی، پنیر تازه، گوجه خشک مزه دارشده (این آیتم به صورت ساده و یا به همراه پروتئین انتخابی سرو میشود‌)",
    price: 527000,
    category: "پاستا",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240254330804605.jpg",
    tag: null,
    ingredients: [],
    note: null,
    variants: [
      {
        id: "pomodoro-pasta-basic",
        nameFa: "ساده",
        nameEn: "Basic",
        price: 527000,
      },
      {
        id: "pomodoro-pasta-with-meat",
        nameFa: "با گوشت",
        nameEn: "With Meat",
        price: 787000,
      },
      {
        id: "pomodoro-pasta-with-chicken",
        nameFa: "با مرغ",
        nameEn: "With Chicken",
        price: 687000,
      },
    ],
    id: "14",
    time: "20 دقیقه",
  },
  {
    slug: "peanut-smoky-pasta",
    nameFa: "پاستا پینات اسموکی",
    nameEn: "Peanut Smoky Pasta",
    description:
      "پنه ریگاته، سس پینات‌ اسموکی برپایه بادمجان‌‌ کبابی، قارچ، بادام زمینی، گوجه خشک مزه دارشده، پنیر پارمسان ( این آیتم به صورت ساده و یا به همراه پروتئین انتخابی سرو میشود‌)",
    price: 537000,
    category: "پاستا",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240254058613355.jpg",
    tag: null,
    ingredients: [],
    note: null,
    variants: [
      {
        id: "peanut-smoky-pasta-basic",
        nameFa: "ساده",
        nameEn: "Basic",
        price: 537000,
      },
      {
        id: "peanut-smoky-pasta-with-meat",
        nameFa: "با گوشت",
        nameEn: "With Meat",
        price: 797000,
      },
      {
        id: "peanut-smoky-pasta-with-chicken",
        nameFa: "با مرغ",
        nameEn: "With Chicken",
        price: 697000,
      },
    ],
    id: "15",
    time: "20 دقیقه",
  },
  {
    slug: "steak-baguette",
    nameFa: "باگت استیک",
    nameEn: "Steak Baguette",
    description:
      "نان باگت فرانسوی، فیله گوساله مزه دار شده، قارچ کاراملایز، کاهو فرانسوی، گوجه خشک مزه دارشده‌، پنیر گودا، زیتون، سس مایوچیز",
    price: 998000,
    category: "باگت",
    image:
      "https://img01.live-app.ir/Files/394/Product/202501041502317698798.jpg",
    tag: null,
    ingredients: [
      "نان باگت فرانسوی",
      "فیله گوساله مزه دار شده",
      "قارچ کاراملایز",
      "کاهو فرانسوی",
      "گوجه خشک مزه دارشده‌",
      "پنیر گودا",
      "زیتون",
      "سس مایوچیز",
    ],
    note: null,
    id: "16",
    time: "20 دقیقه",
  },
  {
    slug: "chicken-baguette",
    nameFa: "باگت مرغ",
    nameEn: "Chicken Baguette",
    description:
      "نان باگت فرانسوی، میکس سینه مرغ مزه دارشده و بیبی اسفناج، کاهو فرانسوی، گوجه خشک مزه دارشده‌، پنیر گودا، زیتون، سس مایوچیز",
    price: 717000,
    category: "باگت",
    image:
      "https://img01.live-app.ir/Files/394/Product/202501041505162343816.jpg",
    tag: null,
    ingredients: [
      "نان باگت فرانسوی",
      "میکس سینه مرغ مزه دارشده و بیبی اسفناج",
      "کاهو فرانسوی",
      "گوجه خشک مزه دارشده‌",
      "پنیر گودا",
      "زیتون",
      "سس مایوچیز",
    ],
    note: null,
    id: "17",
    time: "20 دقیقه",
  },
  {
    slug: "sausage-baguette",
    nameFa: "باگت سوسیس",
    nameEn: "Sausage Baguette",
    description:
      "نان باگت فرانسوی، سوسیس دستساز‌ انجوی‌، کاهو فرانسوی، گوجه خشک مزه دارشده‌، پنیر گودا، زیتون، سس مایوچیز",
    price: 737000,
    category: "باگت",
    image:
      "https://img01.live-app.ir/Files/394/Product/202501041506043466877.jpg",
    tag: null,
    ingredients: [
      "نان باگت فرانسوی",
      "سوسیس دستساز‌ انجوی‌",
      "کاهو فرانسوی",
      "گوجه خشک مزه دارشده‌",
      "پنیر گودا",
      "زیتون",
      "سس مایوچیز",
    ],
    note: null,
    id: "18",
    time: "20 دقیقه",
  },
  {
    slug: "bacon-baguette",
    nameFa: "باگت بیکن",
    nameEn: "Bacon Baguette",
    description:
      "نان باگت فرانسوی، بیکن فیله گوشت، قارچ تفت داده شده، کاهو فرانسوی، گوجه خشک مزه دارشده‌، پنیر گودا، زیتون، سس مایوچیز",
    price: 727000,
    category: "باگت",
    image:
      "https://img01.live-app.ir/Files/394/Product/202501041506532624015.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: [
      "نان باگت فرانسوی",
      "بیکن فیله گوشت",
      "قارچ تفت داده شده",
      "کاهو فرانسوی",
      "گوجه خشک مزه دارشده‌",
      "پنیر گودا",
      "زیتون",
      "سس مایوچیز",
    ],
    note: null,
    id: "19",
    time: "20 دقیقه",
  },
  {
    slug: "mushroom-baguette",
    nameFa: "باگت قارچ و پنیر",
    nameEn: "Mushroom Baguette",
    description:
      "نان باگت فرانسوی، میکس قارچ کاراملایز و اسفناج تفت داده شده، کاهو فرانسوی، گوجه خشک مزه دارشده‌، پنیر گودا، زیتون، سس مایوچیز",
    price: 637000,
    category: "باگت",
    image:
      "https://img01.live-app.ir/Files/394/Product/202501041507213567952.jpg",
    tag: null,
    ingredients: [
      "نان باگت فرانسوی",
      "میکس قارچ کاراملایز و اسفناج تفت داده شده",
      "کاهو فرانسوی",
      "گوجه خشک مزه دارشده‌",
      "پنیر گودا",
      "زیتون",
      "سس مایوچیز",
    ],
    note: null,
    id: "20",
    time: "20 دقیقه",
  },
  {
    slug: "peach-crumble",
    nameFa: "کرامبل هلو",
    nameEn: "Peach Crumble",
    description: null,
    price: 327000,
    category: "دسر",
    image:
      "https://img01.live-app.ir/Files/394/Product/202607260312251333232.jpeg",
    tag: "پیشنهاد ویژه",
    ingredients: [],
    note: null,
    id: "21",
    time: "10-15 دقیقه",
  },
  {
    slug: "lemon-cream-tart",
    nameFa: "تارت لیمو",
    nameEn: "Lemon Cream Tart",
    description: null,
    price: 347000,
    category: "دسر",
    image:
      "https://img01.live-app.ir/Files/394/Product/202607260313286258676.jpeg",
    tag: "پیشنهاد ویژه",
    ingredients: [],
    note: null,
    id: "22",
    time: "10-15 دقیقه",
  },
  {
    slug: "black-forest-tart",
    nameFa: "تارت بلک فارست",
    nameEn: "Black Forest Tart",
    description: null,
    price: 357000,
    category: "دسر",
    image:
      "https://img01.live-app.ir/Files/394/Product/202607260311035415756.jpeg",
    tag: "پیشنهاد ویژه",
    ingredients: [],
    note: null,
    id: "23",
    time: "10-15 دقیقه",
  },
  {
    slug: "berry-cream-tart",
    nameFa: "تارت بری",
    nameEn: "Berry Cream Tart",
    description:
      "تارت بر پایه سبله بروتون و کنفی توت فرنگی و تمشک به همراه موسلین وانیلی و پودر پسته",
    price: 367000,
    category: "دسر",
    image:
      "https://img01.live-app.ir/Files/394/Product/202606212126027236901.jpeg",
    tag: null,
    ingredients: [
      "تارت بر پایه سبله بروتون و کنفی توت فرنگی و تمشک به همراه موسلین وانیلی و پودر پسته",
    ],
    note: null,
    id: "24",
    time: "10-15 دقیقه",
  },
  {
    slug: "matilda-chocolate-cake",
    nameFa: "کیک ماتیلدا",
    nameEn: "Matilda Chocolate Cake",
    description: "کیک اسفنجی شکلاتی به همراه گاناش شکلات تلخ",
    price: 359000,
    category: "دسر",
    image:
      "https://img01.live-app.ir/Files/394/Product/202604032253118193895.png",
    tag: "پیشنهاد ویژه",
    ingredients: ["کیک اسفنجی شکلاتی به همراه گاناش شکلات تلخ"],
    note: null,
    id: "25",
    time: "10-15 دقیقه",
  },
  {
    slug: "cheesecake",
    nameFa: "چیزکیک",
    nameEn: "Cheesecake",
    description: "کیک پنیری با پایه بسکوییت کره ای پخته شده به روش نیویورکی",
    price: 298000,
    category: "دسر",
    image:
      "https://img01.live-app.ir/Files/394/Product/202403132153165111356.jpg",
    tag: null,
    ingredients: ["کیک پنیری با پایه بسکوییت کره ای پخته شده به روش نیویورکی"],
    note: null,
    id: "26",
    time: "10-15 دقیقه",
  },
  {
    slug: "cheesecake-with-hazelnut-chocolate-topping",
    nameFa: "چیزکیک با تاپینگ شکلات فندق",
    nameEn: "Cheesecake with Hazelnut Chocolate Topping",
    description:
      "کیک پنیری با پایه بسکوییت کره ای پخته شده به روش نیویورکی با روکش کرم شکلات فندقی",
    price: 338000,
    category: "دسر",
    image:
      "https://img01.live-app.ir/Files/394/Product/202403132154110124208.jpg",
    tag: null,
    ingredients: [
      "کیک پنیری با پایه بسکوییت کره ای پخته شده به روش نیویورکی با روکش کرم شکلات فندقی",
    ],
    note: null,
    id: "27",
    time: "10-15 دقیقه",
  },
  {
    slug: "cheesecake-with-lotus-topping",
    nameFa: "چیزکیک با تاپینگ لوتوس",
    nameEn: "Cheesecake with Lotus Topping",
    description:
      "کیک پنیری با پایه بسکوییت کره ای پخته شده به روش نیویورکی با روکش کرم بسکوییت لوتوس",
    price: 338000,
    category: "دسر",
    image:
      "https://img01.live-app.ir/Files/394/Product/202403141835033002510.jpg",
    tag: null,
    ingredients: [
      "کیک پنیری با پایه بسکوییت کره ای پخته شده به روش نیویورکی با روکش کرم بسکوییت لوتوس",
    ],
    note: null,
    id: "28",
    time: "10-15 دقیقه",
  },
  {
    slug: "cheesecake-with-peanut-butter-topping",
    nameFa: "چیزکیک با تاپینگ کره بادام زمینی",
    nameEn: "Cheesecake with Peanut Butter Topping",
    description:
      "کیک پنیری با پایه بسکوییت کره ای پخته شده به روش نیویورکی با روکش کره بادام زمینی",
    price: 338000,
    category: "دسر",
    image:
      "https://img01.live-app.ir/Files/394/Product/202403141837027548768.jpg",
    tag: null,
    ingredients: [
      "کیک پنیری با پایه بسکوییت کره ای پخته شده به روش نیویورکی با روکش کره بادام زمینی",
    ],
    note: null,
    id: "29",
    time: "10-15 دقیقه",
  },
  {
    slug: "gummycandy",
    nameFa: "گامی کندی",
    nameEn: "GummyCandy",
    description: "ترکیب ترش و شیرین میوه های استوایی با پس طعم پاستیلی",
    price: 329000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202412240320290240046.jpg",
    tag: null,
    ingredients: ["ترکیب ترش و شیرین میوه های استوایی با پس طعم پاستیلی"],
    note: null,
    id: "30",
    time: "10-15 دقیقه",
  },
  {
    slug: "emerald",
    nameFa: "امرالد",
    nameEn: "Emerald",
    description: "ترکیب میوه های ملس و تابستانه با پس طعم تلخی پرتقال",
    price: 319000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202408062254361029494.jpg",
    tag: null,
    ingredients: ["ترکیب میوه های ملس و تابستانه با پس طعم تلخی پرتقال"],
    note: null,
    id: "31",
    time: "10-15 دقیقه",
  },
  {
    slug: "vin-de-miel",
    nameFa: "وین دِ میل",
    nameEn: "Vin De Miel",
    description: "ترکیب مرکبات و انگور با پس طعم شهد عسل و چای ترش دستساز",
    price: 319000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261911484044616.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: ["ترکیب مرکبات و انگور با پس طعم شهد عسل و چای ترش دستساز"],
    note: null,
    id: "32",
    time: "10-15 دقیقه",
  },
  {
    slug: "mont-parnasse",
    nameFa: "مونت پارناس",
    nameEn: "Mont Parnasse",
    description: "ترکیب ترش میوه های قرمز با پس طعم شیرینی فندق",
    price: 329000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202408062254471812536.jpg",
    tag: null,
    ingredients: ["ترکیب ترش میوه های قرمز با پس طعم شیرینی فندق"],
    note: null,
    id: "33",
    time: "10-15 دقیقه",
  },
  {
    slug: "ete-cool",
    nameFa: "اته کول",
    nameEn: "Eté cool",
    description: "ترکیب بهشتی و خنک میوه های گرمسیری با پس طعم نعنا و لیمو",
    price: 319000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261912013577543.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: ["ترکیب بهشتی و خنک میوه های گرمسیری با پس طعم نعنا و لیمو"],
    note: null,
    id: "34",
    time: "10-15 دقیقه",
  },
  {
    slug: "charlotte",
    nameFa: "شارلوت",
    nameEn: "Charlotte",
    description: "ترکیب میوه های استوایی با هم آمیزی انار و ذغال اخته",
    price: 329000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261912140766419.jpg",
    tag: null,
    ingredients: ["ترکیب میوه های استوایی با هم آمیزی انار و ذغال اخته"],
    note: null,
    id: "35",
    time: "10-15 دقیقه",
  },
  {
    slug: "lilin",
    nameFa: "لیلین",
    nameEn: "Lilin",
    description: "ترکیب ترش و شیرین میوه های قرمز با چاشنی نمک",
    price: 319000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261912242642824.jpg",
    tag: null,
    ingredients: ["ترکیب ترش و شیرین میوه های قرمز با چاشنی نمک"],
    note: null,
    id: "36",
    time: "10-15 دقیقه",
  },
  {
    slug: "grenouille",
    nameFa: "گرنوی",
    nameEn: "Grenouille",
    description: "ترکیب سرحال کننده مرکبات و آلو ها با مکمل انرژی زا",
    price: 339000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261912560459831.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: ["ترکیب سرحال کننده مرکبات و آلو ها با مکمل انرژی زا"],
    note: null,
    id: "37",
    time: "10-15 دقیقه",
  },
  {
    slug: "denis",
    nameFa: "دنیس",
    nameEn: "Denis",
    description: "ترکیب سیب و پرتقال با چاشنی شهد زنجبیل دستساز اسپایسی",
    price: 349000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261913080305269.jpg",
    tag: null,
    ingredients: ["ترکیب سیب و پرتقال با چاشنی شهد زنجبیل دستساز اسپایسی"],
    note: null,
    id: "38",
    time: "10-15 دقیقه",
  },
  {
    slug: "orange-cool-up",
    nameFa: "آب پرتقال",
    nameEn: "Orange Cool up",
    description: "آب پرتقال طبیعی",
    price: 270000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202511031815379156156.jpeg",
    tag: null,
    ingredients: ["آب پرتقال طبیعی"],
    note: null,
    id: "39",
    time: "10-15 دقیقه",
  },
  {
    slug: "red-cool-up",
    nameFa: "آب هندوانه",
    nameEn: "Red Cool up",
    description: "آب هندوانه طبیعی",
    price: 210000,
    category: "ماكتيل",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505241653327787325.JPG",
    tag: null,
    ingredients: ["آب هندوانه طبیعی"],
    note: null,
    id: "40",
    time: "10-15 دقیقه",
  },
  {
    slug: "doppio",
    nameFa: "دوپیو",
    nameEn: "Doppio",
    description: "50 الی 60 میلی لیتر قهوه عصاره گیری شده تحت فشار",
    price: 207000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 207000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 237000,
      },
    ],
    id: "41",
    time: "10-15 دقیقه",
  },
  {
    slug: "americano",
    nameFa: "آمریکانو",
    nameEn: "Americano",
    description: "قهوه دوپیو همراه با مقدار دلخواه آب دمای 80 درجه",
    price: 207000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "آب گرم"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 207000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 237000,
      },
    ],
    id: "42",
    time: "10-15 دقیقه",
  },
  {
    slug: "cappuccino",
    nameFa: "کاپوچینو",
    nameEn: "Cappuccino",
    description: "قهوه دوپیو همراه با 150 میلی لیتر شیر و فوم شیر حجیم",
    price: 297000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "شیر گرم"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 297000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 327000,
      },
    ],
    id: "43",
    time: "10-15 دقیقه",
  },
  {
    slug: "caffè-latte",
    nameFa: "لاته",
    nameEn: "Caffè Latte",
    description: "قهوه دوپیو همراه با 280 میلی لیتر شیر با فوم شیر اندک",
    price: 337000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "شیر گرم"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 337000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 367000,
      },
    ],
    id: "44",
    time: "10-15 دقیقه",
  },
  {
    slug: "caffè-mocha",
    nameFa: "موکا",
    nameEn: "Caffè Mocha",
    description: "قهوه دوپیو همراه با سس شکلات و شیر با فوم شیر اندک",
    price: 367000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "شیر گرم", "سس شکلات"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 367000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 397000,
      },
    ],
    id: "45",
    time: "10-15 دقیقه",
  },
  {
    slug: "caffè-macchiato",
    nameFa: "ماکیاتو",
    nameEn: "Caffè Macchiato",
    description: "قهوه دوپیو همراه با 60 میلی لیتر شیر و فوم اندک",
    price: 277000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "شیر گرم"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 277000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 307000,
      },
    ],
    id: "46",
    time: "10-15 دقیقه",
  },
  {
    slug: "Affogato",
    nameFa: "آفوگاتو",
    nameEn: "Affogato",
    description: "قهوه دوپیو همراه با دو اسکوپ بستنی وانیلی",
    price: 347000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "بستنی وانیل"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 347000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 377000,
      },
    ],
    id: "47",
    time: "10-15 دقیقه",
  },
  {
    slug: "iced-americano",
    nameFa: "آیسد آمریکانو",
    nameEn: "Iced Americano",
    description: "قهوه دوپیو همراه با آب و یخ",
    price: 207000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "آب", "یخ"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 207000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 237000,
      },
    ],
    id: "48",
    time: "10-15 دقیقه",
  },
  {
    slug: "iced-latte",
    nameFa: "آیسد لاته",
    nameEn: "Iced Latte",
    description: "قهوه دوپیو همراه با شیر و یخ",
    price: 337000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "شیر", "یخ"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 337000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 367000,
      },
    ],
    id: "49",
    time: "10-15 دقیقه",
  },
  {
    slug: "iced-mocha",
    nameFa: "آیسد موکا",
    nameEn: "Iced Mocha",
    description: "قهوه دوپیو همراه شیر و سس شکلات و یخ",
    price: 367000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "شیر", "یخ", "سس شکلات"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 367000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 397000,
      },
    ],
    id: "50",
    time: "10-15 دقیقه",
  },
  {
    slug: "iced-coconut-latte",
    nameFa: "آیسد لاته نارگیل",
    nameEn: "Iced Coconut Latte",
    description: "قهوه دوپیو همراه با شیر نارگیل و یخ",
    price: 367000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242033350505039.jpeg",
    tag: null,
    ingredients: ["اسپرسو", "شیر نارگیل", "یخ"],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کامرشیال",
        nameEn: "Commercial",
        price: 367000,
      },
      {
        id: "single-origin",
        nameFa: "سینگل اورجین",
        nameEn: "Single Origin",
        price: 397000,
      },
    ],
    id: "51",
    time: "10-15 دقیقه",
  },
  {
    slug: "coffee-tonic",
    nameFa: "کافی تونیک",
    nameEn: "Coffee Tonic",
    description: "300 میلی لیتر قهوه عصاره گیری شده با یخ و آب سرد گازدار",
    price: 289000,
    category: "نوشیدنی بر پایه اسپرسو",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242027060319770.jpeg",
    tag: "پیشنهاد ویژه",
    ingredients: ["قهوه سرد دم"],
    note: null,
    id: "52",
    time: "10-15 دقیقه",
  },
  {
    slug: "v60-drip-coffee",
    nameFa: "قهوه V60",
    nameEn: "V60 Drip Coffee",
    description:
      "کلمبیا فینکا پروس‌ براوس‌ قهوه‌ای خاص از کشور کلمبیا، منطقه انتیوکیا که در ارتفاع 1750 متری از سطح دریا در قاره آمریکا کشت می‌شود. این قهوه با فرآوری طبیعی همراه با تخمیر بی هوازی ترکیب طعمی منحصر‌به‌فرد، تجربه‌ای غنی و متعادل را ارائه می‌دهد. کشور: کلمبیا منطقه: انتیوکیا ارتفاع: 1750 متر از سطح دریا زیرگونه: کاتورا - کاستیلو فرآوری: طبیعی همراه با تخمیر بی هوازی‌ نمره ارزیابی: 87 طعم یاد:بلک بری ٫ کشمش ٫ کاکائو",
    price: 479000,
    category: "قهوه هاى دمى",
    image:
      "https://img01.live-app.ir/Files/394/Product/202502040025447391915.jpg",
    tag: null,
    ingredients: ["قهوه دم آوری شده"],
    note: null,
    variants: [
      {
        id: "single-cup",
        nameFa: "یک فنجان",
        nameEn: "Single Cup",
        price: 479000,
      },
      {
        id: "double-cup",
        nameFa: "دو فنجان",
        nameEn: "Double Cup",
        price: 579000,
      },
    ],
    id: "53",
    time: "10-15 دقیقه",
  },
  {
    slug: "ibrik-coffee",
    nameFa: "ایبریک کافی",
    nameEn: "Ibrik Coffee",
    description: "قهوه دم آوری شده در جذوه به روش غوطه وری (قهوه ترک)",
    price: 189000,
    category: "قهوه هاى دمى",
    image: "https://img01.live-app.ir",
    tag: null,
    ingredients: ["قهوه ترک"],
    note: null,
    id: "54",
    time: "10-15 دقیقه",
  },
  {
    slug: "creamnut-frappe",
    nameFa: "فراپه شکلات فندق",
    nameEn: "CreamNut Frappe",
    description: "ترکیب قهوه ، شیر ، شکلات فندقی، یخ و خامه حجیم شده",
    price: 479000,
    category: "فراپه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202408062301347180694.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: ["قهوه", "شیر", "شکلات فندقی", "یخ ", "خامه حجیم شده"],
    note: null,
    id: "55",
    time: "10-15 دقیقه",
  },
  {
    slug: "cocomoco-frappe",
    nameFa: "فراپه کوکو موکو",
    nameEn: "CocoMoco Frappe",
    description: "ترکیب قهوه، شیر نارگیل، طعم دهنده افرا، یخ و خامه حجیم شده",
    price: 457000,
    category: "فراپه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202408062302593598384.jpg",
    tag: null,
    ingredients: ["قهوه", "شیر نارگیل", "سیروپ افرا", "یخ ", "خامه حجیم شده"],
    note: null,
    id: "56",
    time: "10-15 دقیقه",
  },
  {
    slug: "biscoff-frappe",
    nameFa: "بیسکو فراپه",
    nameEn: "Biscoff Frappe",
    description: "ترکیب قهوه ، شیر، کرم بیسکوییتی، یخ، خامه حجیم شده",
    price: 457000,
    category: "فراپه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250119254357869.JPG",
    tag: null,
    ingredients: ["قهوه", "شیر", "کرم بیسکوییت", "یخ ", "خامه حجیم شده"],
    note: null,
    id: "57",
    time: "10-15 دقیقه",
  },
  {
    slug: "chocoberry-frappe",
    nameFa: "فراپه شوکو بری",
    nameEn: "ChocoBerry Frappe",
    description:
      "ترکیب قهوه، شیر ، پودر شکلات، کنفی توت فرنگی، یخ و خامه حجیم شده",
    price: 487000,
    category: "فراپه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250124524880306.JPG",
    tag: null,
    ingredients: ["قهوه", "شیر", "توت فرنگی", "یخ ", "خامه حجیم شده"],
    note: null,
    id: "58",
    time: "10-15 دقیقه",
  },
  {
    slug: "peanutbutter-frappe",
    nameFa: "فراپه کره بادام زمینی",
    nameEn: "PeanutButter Frappe",
    description:
      "ترکیب قهوه، شیر، کره بادام زمینی، بادام زمینی نمکی، یخ و خامه حجیم شده",
    price: 447000,
    category: "فراپه",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250129378849150.JPG",
    tag: null,
    ingredients: [
      "قهوه",
      "شیر",
      "کره بادام زمینی",
      "بادام زمینی",
      "یخ ",
      "خامه حجیم شده",
    ],
    note: null,
    id: "59",
    time: "10-15 دقیقه",
  },
  {
    slug: "butternut-shake",
    nameFa: "شیک باترنات",
    nameEn: "Butternut Shake",
    description:
      "ترکیب بستنی کَره ای همراه با مغزیجات گردو و فندق و ارده غنی شده",
    price: 417000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202311121419209819565.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: [
      "ترکیب بستنی کَره ای همراه با مغزیجات گردو و فندق و ارده غنی شده",
    ],
    note: null,
    id: "60",
    time: "10-15 دقیقه",
  },
  {
    slug: "sale-sucre-shake",
    nameFa: "شیک ساله سوکره",
    nameEn: "Salé Sucré Shake",
    description: "شیک شور و شیرین همراه با بادام زمینی نمکی",
    price: 407000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202311121419349662551.jpg",
    tag: null,
    ingredients: ["شیک شور و شیرین همراه با بادام زمینی نمکی"],
    note: null,
    id: "61",
    time: "10-15 دقیقه",
  },
  {
    slug: "figgy-shake",
    nameFa: "شیک انجیر",
    nameEn: "Figgy Shake",
    description: "ترکیب بستنی وانیلی و موز به همراه پوره انجیر و شیر نارگیل",
    price: 427000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250140039090132.JPG",
    tag: "پیشنهاد ویژه",
    ingredients: ["ترکیب بستنی وانیلی و موز به همراه پوره انجیر و شیر نارگیل"],
    note: null,
    id: "62",
    time: "10-15 دقیقه",
  },
  {
    slug: "classic-chocolate-milkshake",
    nameFa: "شیک شکلات",
    nameEn: "Classic Chocolate Milkshake",
    description: "میلک شیک شکلاتی",
    price: 357000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250148040532173.JPG",
    tag: null,
    ingredients: ["میلک شیک شکلاتی"],
    note: null,
    id: "63",
    time: "10-15 دقیقه",
  },
  {
    slug: "coffee-milkshake",
    nameFa: "شیک قهوه",
    nameEn: "Coffee Milkshake",
    description: "بستنی وانیلی به همراه دو شات اسپرسو",
    price: 357000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250151568992557.JPG",
    tag: null,
    ingredients: ["بستنی وانیلی به همراه دو شات اسپرسو"],
    note: null,
    id: "64",
    time: "10-15 دقیقه",
  },
  {
    slug: "lotus-milkshake",
    nameFa: "شیک لوتوس",
    nameEn: "Lotus Milkshake",
    description: "ترکیب بستنی وانیلی به همراه کرم لوتوس و بیسکوییت",
    price: 343000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250155438553513.JPG",
    tag: null,
    ingredients: ["ترکیب بستنی وانیلی به همراه کرم لوتوس و بیسکوییت"],
    note: null,
    id: "65",
    time: "10-15 دقیقه",
  },
  {
    slug: "strawberry-milkshake",
    nameFa: "شیک توت فرنگی",
    nameEn: "Strawberry Milkshake",
    description: "میلک شیک وانیلی به همراه توت فرنگی تازه",
    price: 339000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505301527331587757.JPG",
    tag: null,
    ingredients: ["میلک شیک وانیلی به همراه توت فرنگی تازه"],
    note: null,
    id: "66",
    time: "10-15 دقیقه",
  },
  {
    slug: "solaire-smoothie",
    nameFa: "اسموتی سولایر",
    nameEn: "Solaire Smoothie",
    description: "ترکیب پر ویتامین انبه و پرتقال",
    price: 395000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202311121419488724355.jpg",
    tag: null,
    ingredients: ["ترکیب پر ویتامین انبه و پرتقال"],
    note: null,
    id: "67",
    time: "10-15 دقیقه",
  },
  {
    slug: "nutella-milkshake",
    nameFa: "شیک نوتلا",
    nameEn: "Nutella Milkshake",
    description: "ترکیب بستنی وانیلی به همراه کرم شکلات فندقی",
    price: 349000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250159372030844.JPG",
    tag: "پیشنهاد ویژه",
    ingredients: ["ترکیب بستنی وانیلی به همراه کرم شکلات فندقی"],
    note: null,
    id: "68",
    time: "10-15 دقیقه",
  },
  {
    slug: "salt-berry-smoothie",
    nameFa: "اسموتی سالت بری",
    nameEn: "Salt Berry Smoothie",
    description:
      "ترکیب جذاب توت فرنگی و آلبالو همراه با چاشنی ماست جنگلی و نمک",
    price: 399000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202311121422203412974.jpg",
    tag: null,
    ingredients: [
      "ترکیب جذاب توت فرنگی و آلبالو همراه با چاشنی ماست جنگلی و نمک",
    ],
    note: null,
    id: "69",
    time: "10-15 دقیقه",
  },
  {
    slug: "sun-peach-smoothie",
    nameFa: "اسموتی سان پیچ",
    nameEn: "Sun Peach Smoothie",
    description: "ترکیب تابستانه هلو و شلیل همراه با پوره آلو زرد",
    price: 387000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202408062305575185269.jpg",
    tag: null,
    ingredients: ["ترکیب تابستانه هلو و شلیل همراه با پوره آلو زرد"],
    note: null,
    id: "70",
    time: "10-15 دقیقه",
  },
  {
    slug: "ete-rouge-smoothie",
    nameFa: "اسموتی اته روژ",
    nameEn: "Ete Rouge Smoothie",
    description: "ترکیب جذاب پرتقال و توت فرنگی تازه",
    price: 379000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202408062305433777186.jpg",
    tag: null,
    ingredients: ["ترکیب جذاب پرتقال و توت فرنگی تازه"],
    note: null,
    id: "71",
    time: "10-15 دقیقه",
  },
  {
    slug: "inferno-smoothie",
    nameFa: "اسموتی اینفرنو",
    nameEn: "Inferno Smoothie",
    description: "ترکیب شلیل و تمشک جنگلی به همراه پوره آلو قرمز",
    price: 397000,
    category: "شیک و اسموتی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202408062305173304968.jpg",
    tag: null,
    ingredients: ["ترکیب شلیل و تمشک جنگلی به همراه پوره آلو قرمز"],
    note: null,
    id: "72",
    time: "10-15 دقیقه",
  },
  {
    slug: "matcha",
    nameFa: "ماچا",
    nameEn: "Matcha",
    description: "ماچا",
    price: 299000,
    category: "ماچا",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505141913069504635.jpg",
    tag: null,
    ingredients: ["ماچا"],
    note: null,
    id: "73",
    time: "10-15 دقیقه",
  },
  {
    slug: "iced-matcha",
    nameFa: "آیسد ماچا",
    nameEn: "Iced Matcha",
    description: "ماچا دم آوری شده همراه آب یخ",
    price: 299000,
    category: "ماچا",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505141934245587799.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: ["ماچا دم آوری شده همراه آب یخ"],
    note: null,
    id: "74",
    time: "10-15 دقیقه",
  },
  {
    slug: "matcha-latte",
    nameFa: "ماچا لاته",
    nameEn: "Matcha Latte",
    description: "ماچا دم آوری شده به همراه شیر داغ",
    price: 367000,
    category: "ماچا",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505141945168403121.jpg",
    tag: null,
    ingredients: ["ماچا دم آوری شده به همراه شیر داغ"],
    note: null,
    id: "75",
    time: "10-15 دقیقه",
  },
  {
    slug: "iced-matcha-latte",
    nameFa: "آیسد ماچا لاته",
    nameEn: "Iced Matcha Latte",
    description: "ماچا دم آوری شده همراه با شیر و یخ",
    price: 367000,
    category: "ماچا",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505141935351232245.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: ["ماچا دم آوری شده همراه با شیر و یخ"],
    note: null,
    id: "76",
    time: "10-15 دقیقه",
  },
  {
    slug: "matchagatto",
    nameFa: "ماچاگاتو",
    nameEn: "MatchaGatto",
    description: "ماچا دم آوری شده بر روی دو اسکوپ بستنی",
    price: 369000,
    category: "ماچا",
    image:
      "https://img01.live-app.ir/Files/394/Product/202506031706480036187.JPG",
    tag: "پیشنهاد ویژه",
    ingredients: ["ماچا دم آوری شده بر روی دو اسکوپ بستنی"],
    note: null,
    id: "77",
    time: "10-15 دقیقه",
  },
  {
    slug: "matcha-milkshake",
    nameFa: "شیک ماچا",
    nameEn: "Matcha MilkShake",
    description: "ماچا دم آوری شده ترکیب شده با بستنی وانیلی",
    price: 379000,
    category: "ماچا",
    image:
      "https://img01.live-app.ir/Files/394/Product/202506031708170048149.JPG",
    tag: null,
    ingredients: ["ماچا دم آوری شده ترکیب شده با بستنی وانیلی"],
    note: null,
    id: "78",
    time: "10-15 دقیقه",
  },
  {
    slug: "mango-matcha",
    nameFa: "منگو ماچا",
    nameEn: "Mango Matcha",
    description: "ماچا دم آوری شده به همراه شیر و پوره انبه",
    price: 429000,
    category: "ماچا",
    image:
      "https://img01.live-app.ir/Files/394/Product/202506031709546936277.JPG",
    tag: null,
    ingredients: ["ماچا دم آوری شده به همراه شیر و پوره انبه"],
    note: null,
    id: "79",
    time: "10-15 دقیقه",
  },
  {
    slug: "passion-lime",
    nameFa: "پشن لایم",
    nameEn: "Passion Lime",
    description: "ترکیب لیمو و زردآلو با پشن فروت گازدار",
    price: 298000,
    category: "نوشیدنی گازدار",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250216541855669.JPG",
    tag: null,
    ingredients: ["ترکیب لیمو و زردآلو با پشن فروت گازدار"],
    note: null,
    id: "80",
    time: "10-15 دقیقه",
  },
  {
    slug: "poire-petite",
    nameFa: "پویر پتیت",
    nameEn: "Poire Petite",
    description: "ترکیب لیمو و سیب سبز با آب گلابی گازدار",
    price: 298000,
    category: "نوشیدنی گازدار",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250216219038884.JPG",
    tag: "پیشنهاد ویژه",
    ingredients: ["ترکیب لیمو و سیب سبز با آب گلابی گازدار"],
    note: null,
    id: "81",
    time: "10-15 دقیقه",
  },
  {
    slug: "cherry-berry",
    nameFa: "چری بری",
    nameEn: "Cherry Berry",
    description: "ترکیب آب آلبالو گاز دار به همراه توت فرنگی با پس طعم گیلاس",
    price: 298000,
    category: "نوشیدنی گازدار",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250206514430266.JPG",
    tag: null,
    ingredients: ["ترکیب آب آلبالو گاز دار به همراه توت فرنگی با پس طعم گیلاس"],
    note: null,
    id: "82",
    time: "10-15 دقیقه",
  },
  {
    slug: "mojito",
    nameFa: "موهیتو",
    nameEn: "Mojito",
    description: "ترکیب لیمو و نعنا با آب گازدار",
    price: 249000,
    category: "نوشیدنی گازدار",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250219118591058.JPG",
    tag: null,
    ingredients: ["ترکیب لیمو و نعنا با آب گازدار"],
    note: null,
    id: "83",
    time: "10-15 دقیقه",
  },
  {
    slug: "lemonade",
    nameFa: "لیموناد",
    nameEn: "Lemonade",
    description: "ترکیب لیمو و آب گازدار",
    price: 245000,
    category: "نوشیدنی گازدار",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505250219318437554.JPG",
    tag: null,
    ingredients: ["ترکیب لیمو و آب گازدار"],
    note: null,
    id: "84",
    time: "10-15 دقیقه",
  },
  {
    slug: "coke",
    nameFa: "کوکا",
    nameEn: "Coke",
    description: "نوشابه",
    price: 80000,
    category: "نوشیدنی گازدار",
    image: "https://img01.live-app.ir",
    tag: null,
    ingredients: ["نوشابه"],
    note: null,
    id: "85",
    time: "10-15 دقیقه",
  },
  {
    slug: "fanta",
    nameFa: "فانتا",
    nameEn: "Fanta",
    description: "نوشابه",
    price: 80000,
    category: "نوشیدنی گازدار",
    image: "https://img01.live-app.ir",
    tag: null,
    ingredients: ["نوشابه"],
    note: null,
    id: "86",
    time: "10-15 دقیقه",
  },
  {
    slug: "ardental",
    nameFa: "آردنتال",
    nameEn: "Ardental",
    description: "ترکیب ماسالا هندی با جنسینگ و خشخاش و شیر",
    price: 319000,
    category: "نوشیدنی های گرم",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261914073594402.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: ["ترکیب ماسالا هندی با جنسینگ و خشخاش و شیر"],
    note: null,
    id: "87",
    time: "10-15 دقیقه",
  },
  {
    slug: "coco-chocolate",
    nameFa: "کوکو چاکلت",
    nameEn: "Coco Chocolate",
    description: "ترکیب مخملی شکلات فیلتر شده با شیر",
    price: 297000,
    category: "نوشیدنی های گرم",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261913560936676.jpg",
    tag: null,
    ingredients: [],
    note: null,
    variants: [
      {
        id: "basic",
        nameFa: "ساده",
        nameEn: "Basic",
        price: 297000,
      },
      {
        id: "with-marshmallow",
        nameFa: "با مارشمالو",
        nameEn: "With Marshmallow",
        price: 352000,
      },
      {
        id: "with-cream",
        nameFa: "با خامه",
        nameEn: "With cream",
        price: 357000,
      },
    ],
    id: "88",
    time: "10-15 دقیقه",
  },
  {
    slug: "pink-chocolate",
    nameFa: "پینک چاکلت",
    nameEn: "Pink Chocolate",
    description: "ترکیب صورتی توت فرنگی با شکلات سفید و شیر به همراه مارشمالو",
    price: 299000,
    category: "نوشیدنی های گرم",
    image:
      "https://img01.live-app.ir/Files/394/Product/202506031721082340623.jpg",
    tag: null,
    ingredients: [
      "ترکیب صورتی توت فرنگی با شکلات سفید و شیر به همراه مارشمالو",
    ],
    note: null,
    id: "89",
    time: "10-15 دقیقه",
  },
  {
    slug: "matchate",
    nameFa: "ماچاته",
    nameEn: "Matchate",
    description: "هم آمیزی ماچا ، پسته و شکلات سفید با شیر",
    price: 327000,
    category: "نوشیدنی های گرم",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261914297347430.jpg",
    tag: null,
    ingredients: ["هم آمیزی ماچا", "پسته و شکلات سفید با شیر"],
    note: null,
    id: "90",
    time: "10-15 دقیقه",
  },
  {
    slug: "tea-latte-caramel",
    nameFa: "چای لاته کارامل",
    nameEn: "Tea Latte Caramel",
    description: "ترکیب شیرین عصاره چای و کارامل با شیر",
    price: 289000,
    category: "نوشیدنی های گرم",
    image:
      "https://img01.live-app.ir/Files/394/Product/202402282107455114695.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: ["ترکیب شیرین عصاره چای و کارامل با شیر"],
    note: null,
    id: "91",
    time: "10-15 دقیقه",
  },
  {
    slug: "special-black-tea",
    nameFa: "چای سیاه مخصوص",
    nameEn: "Special Black Tea",
    description: "ترکیب چای بهاره لاهیجان و فومنات",
    price: 159000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202308261923206483295.jpg",
    tag: null,
    ingredients: ["ترکیب چای بهاره لاهیجان و فومنات"],
    note: null,
    id: "92",
    time: "10-15 دقیقه",
  },
  {
    slug: "helin",
    nameFa: "هلین",
    nameEn: "Helin",
    description:
      "ترکیبی از چای سبز چینی ، جازمین و میوه های گرمسیری با طعم یاد عسل",
    price: 197000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202312231321073974068.jpg",
    tag: null,
    ingredients: [
      "ترکیبی از چای سبز چینی",
      "جازمین و میوه های گرمسیری با طعم یاد عسل",
    ],
    note: null,
    id: "93",
    time: "10-15 دقیقه",
  },
  {
    slug: "gabriel",
    nameFa: "گابریل",
    nameEn: "Gabriel",
    description:
      "ترکیب شیرین سیب و پاپایا با همنشینی عطر و طعم دارچین و گل نسترن",
    price: 213000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202312231322089290754.jpg",
    tag: null,
    ingredients: [
      "ترکیب شیرین سیب و پاپایا با همنشینی عطر و طعم دارچین و گل نسترن",
    ],
    note: null,
    id: "94",
    time: "10-15 دقیقه",
  },
  {
    slug: "oten",
    nameFa: "اوتن",
    nameEn: "Oten",
    description: "ترکیبی سرخ از میوه های قرمز با پس طعم بادیان و بهارنارنج",
    price: 217000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202312231322337730007.jpg",
    tag: null,
    ingredients: ["ترکیبی سرخ از میوه های قرمز با پس طعم بادیان و بهارنارنج"],
    note: null,
    id: "95",
    time: "10-15 دقیقه",
  },
  {
    slug: "rozelin",
    nameFa: "روزلین",
    nameEn: "Rozelin",
    description:
      "ترکیب ماندگار آناناس و نارگیل با پس طعم حیرت انگیز رزماری ، خشخاش و زنجبیل",
    price: 213000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202312231323025700741.jpg",
    tag: null,
    ingredients: [
      "ترکیب ماندگار آناناس و نارگیل با پس طعم حیرت انگیز رزماری",
      "خشخاش و زنجبیل",
    ],
    note: null,
    id: "96",
    time: "10-15 دقیقه",
  },
  {
    slug: "marseille",
    nameFa: "مارسلی",
    nameEn: "Marseille",
    description:
      "ترکیب سنتی چای فرانسوی و بادرنجبویه با همنشینی گل سرخ و توت سفید",
    price: 205000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202312231324184924909.jpg",
    tag: null,
    ingredients: [
      "ترکیب سنتی چای فرانسوی و بادرنجبویه با همنشینی گل سرخ و توت سفید",
    ],
    note: null,
    id: "97",
    time: "10-15 دقیقه",
  },
  {
    slug: "landa",
    nameFa: "لاندا",
    nameEn: "Landa",
    description:
      "ترکیب حس آرامش لاوندر فرانسوی و گل گاو زبان با چاشنی گل سرخ و هل و دارچین",
    price: 207000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202312231323488828997.jpg",
    tag: null,
    ingredients: [
      "ترکیب حس آرامش لاوندر فرانسوی و گل گاو زبان با چاشنی گل سرخ و هل و دارچین",
    ],
    note: null,
    id: "98",
    time: "10-15 دقیقه",
  },
  {
    slug: "energisant",
    nameFa: "انرژی زا",
    nameEn: "Énergisant",
    description:
      "ترکیب انرژی بخش چای سیاه و میخک و بادیان به همراه هل و زنجبیل و دارچین",
    price: 219000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202312231331147935543.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: [
      "ترکیب انرژی بخش چای سیاه و میخک و بادیان به همراه هل و زنجبیل و دارچین",
    ],
    note: null,
    id: "99",
    time: "10-15 دقیقه",
  },
  {
    slug: "anti-froid",
    nameFa: "آنتی فروید",
    nameEn: "Anti-Froid",
    description: "ترکیب شفابخش به و به لیمو و اورگانو به همراه رزماری",
    price: 199000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202312231330168397898.jpg",
    tag: "پیشنهاد ویژه",
    ingredients: ["ترکیب شفابخش به و به لیمو و اورگانو به همراه رزماری"],
    note: null,
    id: "100",
    time: "10-15 دقیقه",
  },
  {
    slug: "yerba-mate",
    nameFa: "یربا ماته",
    nameEn: "Yerba Mate",
    description: "ترکیب معجزه گر گیاهان دارویی با پس طعم تنباکو",
    price: 207000,
    category: "دمنوش ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202402282108594342892.jpg",
    tag: null,
    ingredients: ["ترکیب معجزه گر گیاهان دارویی با پس طعم تنباکو"],
    note: null,
    id: "101",
    time: "10-15 دقیقه",
  },
  {
    slug: "berry-iced-tea",
    nameFa: "آیسد تی بری",
    nameEn: "Berry Iced Tea",
    description:
      "ترکیب سرد دَم از چای ترش، آلبالو، زرشک، کرنبری به همراه عصاره چای سیاه",
    price: 217000,
    category: "آیسد تی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242001440206296.jpeg",
    tag: null,
    ingredients: [
      "ترکیب سرد دَم از چای ترش",
      "آلبالو",
      "زرشک",
      "کرنبری به همراه عصاره چای سیاه",
    ],
    note: null,
    id: "102",
    time: "10-15 دقیقه",
  },
  {
    slug: "peach-iced-tea",
    nameFa: "آیسد تی هلو",
    nameEn: "Peach Iced Tea",
    description:
      "ترکیب سرد دَم از زردآلو، هلو، پرتقال، به همراه عصاره چای سیاه",
    price: 217000,
    category: "آیسد تی",
    image:
      "https://img01.live-app.ir/Files/394/Product/202605242005234597671.jpeg",
    tag: null,
    ingredients: [
      "ترکیب سرد دَم از زردآلو",
      "هلو",
      "پرتقال",
      "به همراه عصاره چای سیاه",
    ],
    note: null,
    id: "103",
    time: "10-15 دقیقه",
  },
  {
    slug: "syrup",
    nameFa: "سیروپ",
    nameEn: "Syrup",
    description: null,
    price: 55000,
    category: "افزودنی ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505301559269040296.JPG",
    tag: null,
    ingredients: [],
    note: null,
    variants: [
      {
        id: "commercial",
        nameFa: "کارامل، وانیل، فندق، آیریش، کوکی، توت فرنگی، عسل",
        nameEn: "Caramel,Vanilla,Hazelnut,Irish,Cookie,Strawberry,Honey",
        price: 367000,
      },
    ],
    id: "104",
    time: "10-15 دقیقه",
  },
  {
    slug: "plant-based-milk",
    nameFa: "شیرهای غیر لبنی",
    nameEn: "Plant Based Milk",
    description: null,
    price: 100000,
    category: "افزودنی ها",
    image:
      "https://img01.live-app.ir/Files/394/Product/202505301600158420841.JPG",
    tag: null,
    ingredients: [],
    note: null,
    variants: [
      {
        id: "almond-milk",
        nameFa: "شیر بادام",
        nameEn: "Almond Milk",
        price: 100000,
      },
      {
        id: "oat-milk",
        nameFa: "شیر جو",
        nameEn: "Oat Milk",
        price: 100000,
      },
      {
        id: "hazelnut-milk",
        nameFa: "شیر فندق",
        nameEn: "Hazelnut Milk",
        price: 100000,
      },
      {
        id: "coconut-milk",
        nameFa: "شیر نارگیل",
        nameEn: "Coconut Milk",
        price: 100000,
      },
    ],
    id: "105",
    time: "10-15 دقیقه",
  },
];

export function getMenuItem(slug: string) {
  return menuItems.find((item) => item.slug === slug);
}

export function formatPrice(price: number) {
  return new Intl.NumberFormat("fa-IR").format(price);
}
